Create Database hospitality;
use hospitality;

-- select everything from the table
SELECT *
FROM hospitality;

-- Rename the column name ï»¿reservation_id to reservation_id
ALTER TABLE hospitality
RENAME COLUMN ï»¿reservation_id TO reservation_id;

-- ROOM RATE ANALYSIS
-- What is the average room rate per month
SELECT Months, AVG(Avg_Room_Rate) AS Average_Room_Rate
FROM hospitality
GROUP BY Months
ORDER BY Average_Room_Rate;

-- Which property has the highest and lowest average room rates?
-- For highest
SELECT Property, AVG(Avg_Room_Rate) AS Average_Room_Rate
FROM hospitality
GROUP BY Property
ORDER BY Average_Room_Rate DESC
LIMIT 1;

-- For lowest 
SELECT Property, AVG(Avg_Room_Rate) AS Average_Room_Rate
FROM hospitality
GROUP BY Property
ORDER BY Average_Room_Rate ASC
LIMIT 1;

-- How do the room rates vary between weekdays and weekends?
SELECT Rate_type, AVG(Avg_Room_Rate) AS Average_Room_Rate
FROM hospitality
GROUP BY Rate_Type;

-- RESERVATION AND CHECK-IN ANALYSIS
-- What is the average duration of stay based on the room type and property?
SELECT room_type, Property, AVG(stay_duration) AS average_duration
FROM hospitality
GROUP BY room_type, Property;

-- Is there a correlation between the number of adults/children and the room type?
SELECT room_type, AVG(adults) AS Average_adults, AVG(children) AS Average_children
FROM hospitality
GROUP BY room_type;

-- How does the check-in pattern differ across various booking channels?
SELECT booking_channel, months, COUNT(reservation_id) AS total_bookings
FROM hospitality
GROUP BY booking_channel, months
ORDER BY total_bookings DESC;

-- SPECIAL REQUEST AND BOOKING STATUS
-- How does the completion status relate to special requests?
SELECT reservation_status, special_requests_flag, COUNT(reservation_id) AS total_requests
FROM hospitality
GROUP BY reservation_status, special_requests_flag
ORDER BY total_requests DESC;

-- Which room type or property receives the most special requests?
SELECT room_type, Property, COUNT(reservation_id) AS total_requests
FROM hospitality
WHERE special_requests_flag = 'YES'
GROUP BY room_type, property
ORDER BY total_requests DESC
LIMIT 1;

-- Are special requests more common during weekdays or weekends?
SELECT Rate_Type, special_requests_flag, COUNT(reservation_id) AS total_requests
FROM hospitality
GROUP BY Rate_Type, special_requests_flag
ORDER BY Rate_Type, special_requests_flag DESC;

-- PROPERTY AND RATE TYPE ANALYSIS
-- Which property has the highest occupancy rate or the most bookings?
SELECT Property, COUNT(reservation_id) AS total_bookings
FROM hospitality
GROUP BY Property
ORDER BY total_bookings DESC
LIMIT 1;

-- Compare the rate types across different properties.
SELECT Property, Rate_Type, COUNT(reservation_id) AS total_bookings
FROM hospitality
GROUP BY Property, Rate_Type
ORDER BY Property, Rate_Type;

-- Analyze the advanced booking trends based on the rate type
SELECT Rate_Type, advanced_booking, COUNT(reservation_id) AS total_bookings
FROM hospitality
GROUP BY Rate_Type, advanced_booking
ORDER BY Rate_Type, advanced_booking;

-- CANCELLATION AND NO-SHOW ANALYSIS
-- What's the frequency of no-shows across different properties and room types?
SELECT Property, Room_Type, reservation_status, COUNT(reservation_id) AS no_show_count
FROM hospitality
WHERE reservation_status = 'No-Show'
GROUP BY Property, Room_Type, reservation_status;

-- Do cancellations or no-shows relate to specific booking channels or special requests?
SELECT booking_channel, special_requests_flag, reservation_status, COUNT(reservation_id) AS count_status
FROM hospitality
WHERE reservation_status = 'Cancelled' OR reservation_status = 'No-Show'
GROUP BY booking_channel, special_requests_flag, reservation_status;

-- GEO-LOCATION ANALYSIS
-- Is there a geographical pattern concerning the booking channels or room types?
SELECT Property, booking_channel, COUNT(reservation_id) AS bookings
FROM hospitality
GROUP BY Property, booking_channel;

-- Analyze the distribution of properties based on advanced bookings and room types.
SELECT Property, advanced_booking, Room_Type, COUNT(reservation_id) AS bookings
FROM hospitality
GROUP BY Property, advanced_booking, Room_Type;

-- PERFORMANCE METRICS
-- Calculate revenue generated from each property.
SELECT Property, SUM(Avg_Room_Rate * stay_duration) AS Revenue
FROM hospitality
GROUP BY Property
ORDER BY Revenue DESC;
-- Determine the occupancy rate for each property and room type
SELECT Property, Room_Type, 
       COUNT(reservation_id) AS Total_Bookings,
       SUM(stay_duration) AS Total_Stay_Duration,
       (SUM(stay_duration) / (COUNT(reservation_id)))* 100 AS Occupancy_Rate
FROM hospitality
GROUP BY Property, Room_Type;

-- REVENUE ANALYSIS
-- What is the total revenue generated by each property and room type?
SELECT Property, Room_Type, SUM(Avg_Room_Rate * stay_duration) AS Total_Revenue
FROM hospitality
GROUP BY Property, Room_Type;

-- What is the percentage contribution of each property to the total revenue?
SELECT Property,
    SUM(Avg_Room_Rate * stay_duration) AS Property_Revenue,
    (SUM(Avg_Room_Rate * stay_duration) / (SELECT SUM(Avg_Room_Rate * stay_duration) FROM hospitality)) * 100 AS Percentage_Contribution
FROM hospitality
GROUP BY Property
ORDER BY Property_Revenue, Percentage_Contribution DESC;